name: Build Flutter APK and Web
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Aggiungiamo i permessi per poter pubblicare la pagina web
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      # Abilita il supporto web in Flutter
      - run: flutter config --enable-web
      - run: flutter create . --platforms=android,web
      - run: flutter pub get
      
      # Compila l'APK Android
           - run: flutter pub get

      - name: Generate App Icon
        run: flutter pub run flutter_launcher_icons:main

      - run: flutter build apk --release
      
      - name: Carica APK
        uses: actions/upload-artifact@v4
        with:
          name: app-infiltrazioni-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      # Compila la versione Web
      - run: flutter build web --release --base-href "/app_infiltrazioni/"
      - name: Carica Web App
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  # Pubblica la versione web su un link pubblico
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
